version: '3'

services:
  sisfre_api:
    image: node:18.18.2
    user: 'node'
    container_name: sisfre_api
    depends_on:
      - postgres_sisfre
    ports:
      - '3030:3030'
      - '5555:5555'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres_sisfre:5432/sisfre?schema=public
      - JWT_SECRET=secret
      - NODE_ENV=development
      - PORT=3030
    volumes:
      - ./:/opt/workspace/app
    working_dir: /opt/workspace/app
    networks:
      - postgres-network
    command: yarn start

  postgres_sisfre:
    image: postgres:15
    container_name: postgres_sisfre
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sisfre
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    networks:
      - postgres-network

networks:
  postgres-network:
